
In my sixteen years of life, I was always quick to think love was supposed to be a walk in the park with the sun shining down on you and your lover as you both take in each others company and embrace it for the rest of time. I thought love only took place in movies and it was supposed to make you smile and make you feel as if all the cloudy skies were to turn into the clearest of clear days. Experiences can differentiate your thoughts and opinions about certain things you were definite about before. So let me ask, what exactly is love?
Answers were hard to grasp when there's more than one answer to a simple question. All I seemed to understand was, love can be anything. It can take place anymore, any moment, in anything and also - in anyone. Love was supposed to hurt you. Love was also supposed to make you happiest. Sometimes love is mutual, sometimes love is not. Love can be amazing and love can be dangerous. Love is anything.
Love is also unexpected.
I didn't expect to fall in love, I didn't expect anything at all.
I was able to fall in love with an arrogant, sneaky man who was also full of delight and feelings. A man who was capable to overrun his own mafia and also capable to overrun my heart. Though the way of how I fell in love isn't so delightful or so marvelous, I am not ashamed. I am not ashamed of falling in love.
So as I write in my journal from my bedroom, I can only reminisce in the limited amount of time I got to share with this man. I am ready to say, this is my story.
::
HI OMG , okay so i've decided to make an actual story with an actual plot and setting and everything. I have another story its daddy kink ((-; LOL but i actually wanted to start an actual story with feelings and plot twists and all sorts.
Quick disclaimer, if you are offended or sensitive to sexual content, violence and death - i suggest you click away from this story and read something that suits your criteria. Anyways, hopefully I can update the first chapter today or tmmrw! Im so excited to start this story I tried so hard to make this as original as possible.
But ayyyeee professional sex business harry (;
I hope this prologue was good and hope all of you enjoyed.
