
Soooooo I'm writing this story because 1) I love imprinting 2) I love the way Jared imprinted on Kim 3) I love Larry Stylinson Okay so before you read this, know-Imprinting is a very intense thing. I don't own Twilight, Imprinting or One Direction. Remember this story will mainly be based on imprinting and that's pretty much it. This imprinting story will be Jared and Kim style, that is Harry or Louis (I'm not giving that out yet) will imprint on the other like Jared imprinted on Kim. That's it okay bye let's start.----------
I've never been the one to draw attention to myself. Maybe it's because I speak to only two people or maybe because I spend my time reading a classic on a Friday night when there is party next door.
I wasn't bothered by it, the lesser people I talk to the lesser drama I have in life. That's what I thought and it was true.
In my seventeen years of life, I really didn't have any drama. A normal routine, no fights with the two friends I have whatsoever, no breakups and yeah I loved the simplicity of my life.
But then there was Harry Styles, walking in all his long legged glory. You just simplicity did not not have a crush on Harry Styles. How could you not, when he laughed with dimples- fucking dimples- and had legs so long you wished they were wrapped around you every night. And his eyes, oh god, they were green and twinkled whenever he was amused. I wanted to have a close up of those, like my life depended on it.
"You are staring." My best mate, Niall, whispered in my ears.
I snorted, "I thought I was speaking." My attention now away from Harry who was talking to his "group" of friends not so far away.
You see, Niall was the straightest person you'd ever come across. But I could care less.
"Why don't you just talk to him?" Niall asked, raising an eyebrow.
Yeah, one more fact about me, Harry Styles didn't know I existed. Yes that's right, and let me break it to you- we've been sitting next to each other in our English class for the last three months, plus we've shared one class or the other since we were first graders. Yes he still doesn't know I exist.
"I'm pretty sure we'll strike up a conversation in the next century or so, young Nialler." I said, rolling my eyes.
"Alright, but don't raise a ruckus when you're in your hospital bed and you only got to get an orgasm while looking at his pictures and not him." Niall said, shrugging.
"I do not wank looking at his pictures!" I said, my cheeks burning.
"And I'm not Irish." Niall said, rolling his eyes.
"Whatever, see you at lunch." I said, entering my math class.
I have a strong infatuation with Harry Styles.Yeah, that's what I liked to call it. Everything is good, really, there is just a tiny problem-Harry Styles doesn't know I exist.
That's it.
Nothing's wrong in that.
Right?
•
So how's it? ^_^