
"Every relationship I have ever been in, the guy always acts like I'm not even in their possession and it honestly sucks." I said with tears streaming down my face
"It's okay now, you're all mine baby" He said kissing my temples
✧((sometimes lowercased intended))© All Rights Reserved to whitesideheaven 2015
✦✧✦✧
kayla marie phillips; born on july 17, 1997. 17. sophomore. 20% dominican, 40% african american, and 40% caucasian. long natural curly hair. sweet at heart, fierce when needed to be. currently dating.
✦✧✦✧
jack finnegan gilinsky; born on september 10, 1996. 18. sophomore. 50% mexican jew and 50% caucasian. short quiffed up hair. popular kid. currently single.__________________*I'm pretty excited for this book! Add this to your library please✨•Vote, Comment, & Follow
1 vote💗