
Prologue
---

Four Years Before.
~
Running at my fastest pace, the cold wind split at my skin and on my curls. I barely feel that my feet were hitting the ground because of the terror that is rushing inside of me.

"Styles come here. The Cellar is waiting for you,"

I take a fleeting look around the place and I notice the huge oak tree. I stopped and I rapidly hide behind the broad tree that I think was enough to screen my presence. Panting, I take a quick look on my wristwatch.

6:00 P.M.

The hands of the watch are fixed on the 6 o'clock position. I tried to calm myself and I closed my eyes firmly. The sound of the lightning burst out as the heavy rain continuously pours. The cold droplets of water sprinkled on my face but it didn't do anything or calm me. I opened my eyes once more and heave a sigh.

I'm in the woods. It's been thirty minutes when I started to dash out from my apartment. This stupid lunatic being was chasing me all of the time like she was my personal stalker, not to point out that she was also a killer.

"There you are," my eyes widened when all of a sudden, her figure appears in front of me. Her hair was completely covering her whole face; exclude her whitish but bloody eyes. I can tell that her face was filled of blood; I am adding that she was also ugly as hell.

I cleared my throat and my body posture alters into tensed. "Wh-what do you want!?!" I stuttered, trying to sound firm as I can and I knew I failed. I can tell that she smiled at me since her eyes squinted.
She raised her hands and the surroundings started to blend. I tilted my head all over the place until I realized, I'm back in my apartment. I blinked numerously and the lunatic girl ghost was gone. What was that? A prank show? I sighed in relief and I was about to walk when I noticed that I am holding a book.

"The Cellar?" I raised an eyebrow when I read the cover of the book. I opened the pages but it contains nothing. The pages didn't contain anything and I raised an eyebrow in confusion. I ran my hand throughout my hair and ruffled it.
Scanning entire leaf of the book, a page caught my interest. Finally, the last page contains words on it and written with the use of blood. I blinked numerously and I stared on the words, yet, bamboozled regarding the book.

"My world split into two,
I am accepting the offer of you.
Brought me into the your place,
The place that was bane on the existence the word hope.
I will be ensnared on a place without anything but fear,
Locking myself inside of..."
I stopped reading the words once I noticed a presence in front of me. I stepped backward and she smiled.

"C'mon. Read it dear. That book was amazing," she said, giving the strong stress on the entire word 'amazing'. She raised her hand and a reaper emerges. I instantly return my gaze into the book, ignoring her actions. This words wasn't a poem, sonnet or what. I can feel something odd as I read the words. Every time the words split out on my mouth, something on my body was twisting.

"...The Cellar." I finished and the warm blowing wind alters into cold.
"Goodbye my dear," she whispered on my ear and I felt that my soul was detached on my body. The darkness fills my senses and my body dropped on the ground.