
Me, I wouldn't say I am the nicest person. You piss me off, I become a bitch. People say I am rude, snappy and a bitch. I would say I defend myself and don't take shit from other people. Last year I was vulnerable became friends with the wrong people and done wrong things, before I met those people, you could say I was up tight, well put together and preppy. I have a few piercings and dress how I want. People say that I am just like Luke, Calum and Michael, but unlike them I have self respect and value myself and I don't treat people like shit. I have my best friend Ashton Irwin. I've known Ash for nearly ten years and love him a lot. He's been there for me through thick and thin and he is just amazing.
....
I got changed in to a white crop top and black ripped skinny jeans. Straightened my hair, did my makeup, put my white converse on, sprayed my perfume. I grabbed my bag, chucked a few books, in there put my pencil case, earphones, phone, makeup bag and gum in there and went downstairs. My brother Elijah was downstairs eating cereal. Elijah was 18, two years older than me. We have always been close.
"Hey Sky, you okay?"
"Yeah, just tired, didn't get much sleep last night, you?"
"I'm alright, mum and dad have gone to London for work, they didn't want to wake you, they wont be back for two days"
"ugh, okay...i'm going school now, see you later"
I grabbed my keys and ran out the door. I put my earphones in and was listening to Shawn Mendes. I walked to school and walked through the gates and saw Calum Hood being the asshole he is, push Emily out the way and drop her books.
"do you have to be jerking off so early in the morning?" She said with a disgusted look on her face
"You do know that, that is not the right way to say that right? but yeah I most certainly do" Calum said with a smug look and winked at her.
He's such a jerk...I ran to Emily and picked her books up.
"Are you okay? He's  a dick don't worry about him"
"Yeah I'm fine, thank you sky. See you around" Emily said and walked away.
I started to walk to music with my music blasting in my ears.
//Authors Note//:
Hey lovelies, I'm Molly, clearly the author of this book :)
I just want to say thank you too Lola, who has been helping me write, she's an amazing so thank youuu Lola :))))
I hope you enjoyed this chapter and yeah :) IM EXCITED!!
THANKS GUYS
LOVE MOLLY x