
Calum's P.O.V//
It is Monday again. Why does Monday come around so quickly. I really don't understand. I hate Monday's because I have to sit in that shitty choir room with everyone I could possibly hate, minus a few. Those few being my friends. Luke Hemmings and Michael Clifford. I guess we are known as the 'Jerks That Sing' . If If am being totally honestly, I really like what we are, regardless of what people think.  We wear what we want, have tattoos, piercings and hook up with girls. We have a tradition that we follow by,
-Meet the girl
-Kiss
-Fuck
-Leave that bitch.
Oh yeah, we also sing. Hense why we sit in that shitty choir room with a bunch of annoying, full of life prats that think they can sing but are really far from it. Mr Shue practically forced us to pick music as an option. Don't get me wrong, I love music and playing the bass but Mr Shue and the students in the class piss me off to the max. I hate it. There is one girl in there that is just so snappy and a bitch. I think her names Sky? or Skylar? or SkyBITCH. Something along those lines.
I grab my phone from my bed and see I have received a text from Luke.
Luke : 'you shit brick, where is my Santa Cruz muscle tee?'
Calum : 'Uh, you'll find out when you see me ;)'
Luke : 'Cal, will you come with me tonight to Taylor's party? It's going to be MAAADDD"
Calum : "count me in"
I slid my phone in to my incredibly tight black jeans that are probably Michael's. I bent down to look under my bed for my black converse. Turns out they were in my bed....I looked around the room, there were clothes everywhere, empty cigarette packets, beanies, shoes, red cups and vodka bottles everywhere. I grabbed  a packet of cinnamon gum, put one in my mouth and grabbed by bag and put the rest in there. I turned around and shut my bedroom door which is practically falling apart.
As I walk down my stairs, I feel my phone vibrate in my pocket.
Michael : 'Ummm Calum, do you have my black skinny jeans with the ripped knee? Because if you do just be ready for a punch in the face when I see you!!!! Love You ;) x'
Calum : 'MICHAEL, you know I love you :) *coughipossiblyhaveyoujeansonbutpleasedontpunchmeinthefaceyourethebestiloveyou!!!cough*
....
I finally reached school, I brushed past a girl with extremely long blonde hair, and purposely made her drop her books, and pushed her aside.
"do you have to be jerking off so early in the morning?" She said with a disgusted look on her face
"You do know that, that is not the right way to say that right? but yeah I most certainly do" I winked and walked to my first lesson, chewing my gum with Blink 182 blasting in my ears.
//
Skylar's P.O.V//
It's Monday AGAIN. Why does Monday come around so quickly? The highlight of my Monday would have to be Music in the choir room with Mr Shue. I love music, I love singing and performing. The worst part about Music would be the Jerks that sit at the back of the room constantly talking and chewing, chewing gum irritatingly loud. Calum Hood, Luke Hemmings and Michael Clifford. The jerks that can sing. They hook up with girls and then treat them like shit. They dress however they want, have tattoos, piercings and drink. The worst one out of all three would have to be Calum. He is so rude and arrogant and up his own ass. Me and Calum have hated each other since year 7 when we first met. He pretends to not know my name as he thinks this effects me. He's the biggest jerk in the entire school.