
Coleen's P.O.V
I was with my mum and we're just talking stuff such as cooking and me asking mum how she fell in love with dad and waaaah waaaah waaaah...
That's when my phone rings. It's Michael. Yep Michael Clifford. Him and the boys are actually just my closest friends aside from Abby.
"Hello Mikey?" I smile
"Cole! Hey! Do you forgot to pick us up at the airport?!? The fans are going crazy!" Michael shout through the screaming fans
My eyes wide making mum laugh at me
"Shit! I forgot sorry mike I'm coming in 15 minutes" I quickly ended the call and kiss my mum
"You forgot to pick the boys?" Mum ask laughing and I nod
"I'll re-check if the room they're sleeping in is clean and tidy!" I leave the house with my black Audi SUV heading at the airport.
I was at the airport and shit Michael is not lying about the fans.
They're like tigers screaming for food and the food are the boys.
"Dammit" I muttered as I slowly and safely approach the front of the airport.
A security went at the window and I rolled it down
"Excuse me miss are you Coleen Johnson?" He ask trying to stop the fans to get in the car which I quickly lock.
"Yes and I'm here to pick the four idiots" he raise an eyebrow and said "I'll call their manager" I shrug
Joe know who I'am since I went on tour with them. I few fans went to my car to ask for picture.
Yup even the fans know who I'am. They even ship me with Luke or with Calum which is weird.
I saw Joe approach to me "Coleen are you here to pick the boys up?"
I nod my head "yup they're staying at my house" he nod and said he's going to get the boys
"Told ya" I said in a monotone voice closing my window and laughing a little
Screams grew more louder and I saw the boys. I quickly unlock the doors and open the trunk making it lift automatically.
"Coleen! We've missed you!" Ashton says from the passenger seat hugging me
I laugh and hug him back "miss ya too ash!" The boys clear their throats and I laugh playfully rolling my eyes
"Of course I miss you too guys!!" They cheered and as soon as the trunk closed we quickly (but careful from not hitting anyone) leave the airport.
"So Cole" calum says from the backseat smirking
"Mhm?"
"New car eh?" He smirks and the boys smirks too making me shake my head
"Ohh! Where's the money from??" Ash says
"We can eat here right?" Mike ask and I nod giving him a thumbs up and he cheer
"We can drive it too?" Luke asks
"Oh guys no! Never! Last time you drove my car you guys broke it and that's the reason why I buy a new one" I explain
I get a loads of 'really?' Or 'are you fucking serious?' I chuckle and continue to drive the boys ranting about their tour and how ashton broke quite all the drums
I miss this idiots......
***
"Guys ready for my mum?" I ask them and they nod