
I put the car in the driveway and help the boys with their luggages.
You see every time the boys come to my house my mum treat them like her sons and made them tell her about the tour then end up telling them rules about not doing this not doing that blah blah blah.
"Mum your potatoes are here!!" I shout and the boys chuckle
Mum came out of the kitchen with a big smile and the boys quickly running to her hugging her
"My boys!!! How's tour guys?" Mum asks as we sit on the couch
"It's really fun" Luke says
"Ash broke nearly all of the drums" Calum says and ash rolled his eyes
"We get to learn how to cook" Ash proudly says
"And we made a new song" Michael says
Mum have a surprise look "really can I hear it?" the boys nod their heads
And shout/sing "MICHAEL WANTS ANOTHER SLICE! MICHAEL WANTS ANOTHER SLICE!! MICHAEL WANTS ANOTHER SLICE!!"
"PIZZA!!! PIZZA!!" They all shout/ sing making I and mum smile as their heads and body moves in different ways in every lyrics
"Well I ordered piz-" before mum could finish I and the boys quickly run in the dining room ready to devour the pizza
"Guys!!!!" I shout making them all stop from what they're doing "what?" They innocently ask
"I miss you all" they all shrug except from calum who hug me kissin my cheek saying he missed me back before returning back to devoured the pizza.
I swear I miss this four idiots....
My four idiots :-)